### ISSUE TITLE
"FmSynth.dll is not a valid Win32 application"

### ISSUE THREAD

**Issue by ghost** [fedden/juceSynths#4]
I am running Windows 10 and using Visual Studio 2017. I have tried setting the export target as both Visual Studio 2017 and Visual Studio 2015. I get this error message when I attempt to run with the Local Windows Debugger.

> Unable to start program C:\Users\thomasshera\juceSynths-master\juceSynths-master\FMSynth\Builds\VisualStudio2015\x64\Denig\VST\FmSynth.dll'.

> 'C:\Users\thomasshera\juceSynths-master\juceSynths-master\FMSynth\Builds\VisualStudio2015\x64\Denig\VST\FmSynth.dll' is not a valid Win32 application.

The odd part is that I have 0 errors, only warnings.

Any advice?

**Comment by fedden** [comment]
I'm sorry no; I don't have a windows dev machine; I only use Linux. This code was also for JUCE 4 so will likely need to be updated for that if you haven't already. 

If you do get it working feel free to submit a pull request with the fixes.

All the best!

**Comment by ghost** [comment]
Hey in case any other extreme noobs read this, I seem to have found a solution.

https://forum.juce.com/t/path-plugin-dll-is-not-a-valid-win32-application/16492

Apparently you can only BUILD using Visual Studio- a DAW or the Juce Plugin Host is required to run any JUCE Audio Plugins. I did not realize this because the tutorials I watched involved JUCE Audio Applications which can be ran independently of a DAW haha.
